apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/konflux-build-catalog?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main" && ("pipelines/common-fbc.yaml".pathChanged() || ".tekton/common-pipeline-fbc-pull-request.yaml".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: konflux-build-catalog
    appstudio.openshift.io/component: common-pipeline
    pipelines.appstudio.openshift.io/type: build
  name: common-pipeline-fbc-pull-request
  namespace: crt-redhat-acm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/common-pipeline:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Containerfile.catalog
  - name: path-context
    value: v4.13
  - name: build-platforms
    value:
    - linux/x86_64
  - name: opm-args
    value:
      - alpha
      - render-template
      - basic
      - "v4.13/catalog-template.json"
  - name: opm-output-path
    value: v4.13/catalog/multicluster-global-hub-operator-rh/catalog-current.json
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/stolostron/konflux-build-catalog.git"
      - name: revision
        value: '{{revision}}' # {{revision}} is the commit hash of the PR branch
      - name: pathInRepo
        value: pipelines/common-fbc.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-common-pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
